### ISSUE TITLE
Buried Bones generate in soul stone

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#179]
**Describe the Bug:**
Buried bones cannot be placed on soul stone, yet they are able to generate in them.

**Expected Behavior:**
The buried bones should not spawn in the soul stone.

**Screenshots:**
![image](https://user-images.githubusercontent.com/49106149/126235850-b6fe272b-9fff-4548-8683-f884c47eafb6.png)

**Version Information:**
- Operating System: Windows
- Mod Version: 2.0.0. Beta 7
- Minecraft Version: 1.16.5
- Forge Version: 1.16.5-forge-36.1.0

**Comment by nekomaster1000** [comment]
I don't see this as a massive issue, since the interpretation of Soul Stone I ran on when implementing it was that it's hardened Soul Sand/Soil, so the bones could have been there before the blocks turned to stone. Do you still think they shouldn't generate on it, or should we make it so the bones are placeable in Soul Stone?

**Comment by neoNoteCoder** [comment]
Ah, fair enough. If soul stone is meant to be hardened soil, that seems fine for the bones to be there, Considering that soul stone is, well, stone, being able to plant them would be a bit weird.
