### ISSUE TITLE
2.2 crash broked

### ISSUE THREAD

**Issue by briarss** [nekomaster1000/Infernal-Expansion#258]
**Describe the Bug:**
crash on world load. both new and old world

**How to Reproduce:**
load into the world

**Expected Behavior:**
no crash

**Version Information:**
 - Operating System: windows
 - Mod Version: 2.2
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.0
 - Other mods that were running when the crash happened:

[crash-2021-08-11_01.09.18-client.txt](https://github.com/infernalexp/Infernal-Expansion/files/6965059/crash-2021-08-11_01.09.18-client.txt)

**Comment by SwanX1** [comment]
Did you enable the `replaceNetherBiomeProvider` config?

**Comment by briarss** [comment]
nope, i didnt touch the configs. just updated and it crashed when i tried to join any world.

**Comment by gtokarz** [comment]
same bug here, I am using ATM 6 with added infernal expansion, switching back to 2.1.1 seems to help

**Comment by Klouver-github** [comment]
I am also having same bug as well in 2.2

**Comment by PhweeDev** [comment]
This too happens only in version 2.2.0.

**Comment by SwanX1** [comment]
Fixed in 2b3fb682b9dc96f18492e7740a845fc99f34708e.
<details>
<summary>Mentioned Users</summary>

 - @amoooooo 
 - @gtokarz 
 - @Klouver0X 
 - @Phweeeee 
</details>

Please let me know if using this version of the mod doesn't fix your issue: [infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar](https://infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar)
