### ISSUE TITLE
Crash when trying to rejoin a world after leaving

### ISSUE THREAD

**Issue by InteJason** [nekomaster1000/Infernal-Expansion#274]
When you leave a world and click on re-join, the game crashes. The crash report mentions infernal expansion.

https://pastebin.com/16d0THJV

**Comment by SwanX1** [comment]
Duplicate of #258, fixed in commit 2b3fb682b9dc96f18492e7740a845fc99f34708e
<details>
<summary>Mentioned Users</summary>

 - @InteJason 
</details>

Please let me know if using this version of the mod doesn't fix your issue: [infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar](https://infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar)

**Comment by InteJason** [comment]
tried it, did not fix it: https://pastebin.com/kYweiDnh

**Comment by SwanX1** [comment]
Please post your world's level.dat file

**Comment by SwanX1** [comment]
Closing due to no more information given.
