### ISSUE TITLE
Compatible with Amplified Nether mod [1.19.2]

### ISSUE THREAD

**Issue by SuperFeda** [nekomaster1000/Infernal-Expansion#402]
Faced with the problem of compatibility "Infernal Expansion" and "Amplified Nether" in one modpack.
Basically the generation of the biome from the mod Infernal Expansion, looks like this:

(DeepL Translate)

![2022-11-04_00 32 15](https://user-images.githubusercontent.com/112332753/199797834-293feeb5-d793-4da6-807a-3cb0c7f0dcbb.png)
![2022-11-04_00 33 06](https://user-images.githubusercontent.com/112332753/199797846-c44154c1-e075-4549-a8d5-212d61939375.png)

**Comment by riley-9054** [comment]
To my understanding this is not fixable on Infernal Expansion's end due to how Amplified Nether achieves 3D biomes and the fact it is just a datapack.
I know a way you can fix it, however. Download the actual datapack version of Amplified Nether off Planet Minecraft, unzip it, and then look through the files of it until you find a folder labeled "biome", and delete that folder. This will remove the 3D biomes from Amplified Nether, allowing it to be much more compatible with any modded biomes.

Do keep in mind that despite editing Amplified Nether, you still do not own it and thus cannot legally distribute this edited version. If anyone asks for it, just walk them through how to recreate it.

**Comment by SuperFeda** [comment]
> To my understanding this is not fixable on Infernal Expansion's end due to how Amplified Nether achieves 3D biomes and the fact it is just a datapack. I know a way you can fix it, however. Download the actual datapack version of Amplified Nether off Planet Minecraft, unzip it, and then look through the files of it until you find a folder labeled "biome", and delete that folder. This will remove the 3D biomes from Amplified Nether, allowing it to be much more compatible with any modded biomes.
> 
> Do keep in mind that despite editing Amplified Nether, you still do not own it and thus cannot legally distribute this edited version. If anyone asks for it, just walk them through how to recreate it.

Thanks!
