### ISSUE TITLE
License on Modrinth is incorrect

### ISSUE THREAD

**Issue by triphora** [nekomaster1000/Infernal-Expansion#56]
You use the Apache-2.0 license. However, [your Modrinth page](https://modrinth.com/mod/ZrpxHZN4) displays the license as `ARR` instead of `APACHE`. I assume this was a misclick.

**Comment by SwanX1** [comment]
No, this wasn't a misclick, as we used the ARR license and switched to the Apache License after uploading the mod. It would be misleading to update the page to show that it uses the Apache License because those versions still use the ARR license. The Modrinth and CurseForge pages will be updated with the correct license after we upload the versions that use it.
