### ISSUE TITLE
Using a whip on a dedicated server crashes it.

### ISSUE THREAD

**Issue by SwanX1** [nekomaster1000/Infernal-Expansion#87]
<h2 align="center"><strong>THIS IS A CRITICAL BUG</strong></h2>

Releasing the whip (and thus sending a packet to the server) makes the server crash
Crash Report: [crash-2021-05-02_19.04.57-server.txt](https://paste.gg/p/anonymous/1259ac8ff5e64eb88b02bbfa57c8da90)
Using commit 6a1f518 - **Disabled AvoidBlockGoal for MagmaCubeEntity**

### Additional info:
Minecraft environment: Dedicated server
Allocated RAM: 2GB
Minecraft version: 1.16.5
Forge version: 36.1.16
Operating System: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)
Java: Java 11 (OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04))

**Comment by Dariensg** [comment]
Do we know that the packet is what is actually crashing it? It's possible the method of holding right click actually doesn't use the packet and that's the real reason behind the crash.

I know the packet reach code is also in the whip class. It's possible we actually have to work the packet back into the whip rather than fix a crashing packet. It's possible the crash is actually that the packet isn't being used and needs to be in order to avoid the crash, unless you have a log that says otherwise.
